app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('', views.IndexMain.as_view())
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path(패턴, 매핑) /blog/
    # path("", views.index), # FBV
    # 글 목록 조회
    path("", views.Index.as_view(), name='list'), # /blog/
    # 글 상세 조회
    path("detail/<int:pk>/", views.DetailView.as_view(), name='detail'), # /blog/detail/1
    # 글 작성
    path("write/", views.Write.as_view(), name='write'), # /blog/write/
    # 글 수정
    path("detail/<int:pk>/edit/", views.Update.as_view(), name='edit'),
    # 글 삭제
    path("detail/<int:pk>/delete/", views.Delete.as_view(), name='delete'),
    # 코멘트 작성
    path("detail/<int:pk>/comment/write/", views.CommentWrite.as_view(), name='cm-write'),
    # 코멘트 삭제
    path("detail/comment/<int:pk>/delete/", views.CommentDelete.as_view(), name='cm-delete'),
    # 태그 작성
    path("detail/<int:pk>/hashtag/write/", views.HashTagWrite.as_view(), name='tag-write'),
    # 태그 삭제
    path("detail/<int:pk>/hashtag/delete/", views.HashTagDelete.as_view(), name='tag-delete'),
]

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.content


class HashTag(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    name = models.CharField(max_length=10)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name

blog/forms.py
# blog/forms.py
from django import forms
from .models import Post, Comment, HashTag

# Form: html에 있는 form 태그
# Model Form: model을 사용하는 form
class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['title', 'content']


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'rows': '3', 'cols':'35'})
        }


class HashTagForm(forms.ModelForm):
    
    class Meta:
        model = HashTag
        fields = ['name']

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post, Comment, HashTag
from .forms import PostForm, CommentForm, HashTagForm
from django.urls import reverse_lazy, reverse

# Create your views here.
# def index(request):
#     if request.method == 'GET':
#         return HttpResponse('Index page GET')
#     # 나머지 요청
#     # 에러, 예외처리
#     return HttpResponse('No!!!')

### Post
class Index(View):
    def get(self, request):
        # return HttpResponse('Index page GET class')
        
        # 데이터베이스에 접근해서 값을 가져와야 합니다.
        # 게시판에 글들을 보여줘야하기 때문에 데이터베이스에서 "값 조회"
        # MyModel.objects.all()
        post_objs = Post.objects.all()
        # context = 데이터베이스에서 가져온 값
        context = {
            "posts": post_objs,
            "title": "Blog"
        }
        # print(post_objs) QuerySet<[post 1, 2, 3, 4, 5]>
        return render(request, 'blog/post_list.html', context)

'''
class Index(LoginRequiredMixin, View):
    def get(self, request):
        # Post - User 연결 (Foreignkey)
        # User를 이용해서 Post를 가지고 온다.
        posts = Post.objects.filter(writer=reuqust.user)
        context = {
            "posts": posts
        }
        return render(request, 'blog/post_list.html', context)
'''


# write
# post - form
# 글 작성 화면
# def write(request):
#     if request.method == 'POST':
#         # form 확인
#         form = PostForm(request.POST)
#         if form.is_valid():
#             post = form.save()
#             return redirect('blog:list')

#     form = PostForm()
#     return render(request, 'blog/post_form.html', { 'form': form })


# Django 자체의 클래스 뷰 기능도 강력, 편리
# model, template_name, context_object_name,
# paginate_by, form_class, form_valid(), get_queryset()
# django.views.generic -> ListView
# class List(ListView):
#     model = Post # 모델
#     template_name = 'blog/post_list.html' # 템플릿
#     context_object_name = 'posts' # 변수 값의 이름


# class Write(CreateView):
#     model = Post # 모델
#     form_class = PostForm # 폼
#     success_url = reverse_lazy('blog:list') # 성공시 보내줄 url

class Write(LoginRequiredMixin, View):
    # Mixin: LoginRequiredMixin -> 로그인되지 않은 사용자가 /login
    # login_url = '/user/login'
    # redirect_field_name = 'next' 
    
    def get(self, request):
        # next_path = request.GET.get('next')
        # next_url = request.GET.get(self.redirect_field_name)
        
        form = PostForm()
        context = {
            'form': form,
            "title": "Blog"
        }
        return render(request, 'blog/post_form.html', context)
    
    def post(self, request): # request -> HttpRequest 객체
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False) # commit=False 변수 할당만 우선 하고 이후에 수정가능
            post.writer = request.user
            post.save()
            return redirect('blog:list') # response -> HttpResponse 객체
        form.add_error(None, '폼이 유효하지 않습니다.')
        context = {
            'form': form
        }
        return render(request, 'blog/post_form.html')


# class Detail(DetailView):
#     model = Post
#     template_name = 'blog/post_detail.html'
#     context_object_name = 'post'


# class Update(UpdateView):
#     model = Post
#     template_name = 'blog/post_edit.html'
#     fields = ['title', 'content']
#     # success_url = reverse_lazy('blog:list')
    
#     # intial 기능 사용 -> form에 값을 미리 넣어주기 위해서
#     def get_initial(self):
#         initial = super().get_initial() # UpdateView(generic view)에서 제공하는 initial(딕셔너리)
#         post = self.get_object() # pk 기반으로 객체를 가져옴
#         initial['title'] = post.title
#         initial['content'] = post.content
#         return initial
    
#     def get_success_url(self): # get_absolute_url
#         post = self.get_object() # pk 기반으로 현재 객체 가져오기
#         return reverse('blog:detail', kwargs={ 'pk': post.pk })


class Update(View):
    def get(self, request, pk): # post_id
        post = Post.objects.get(pk=pk)
        form = PostForm(initial={'title': post.title, 'content': post.content})
        context = {
            'form': form,
            'post': post,
            "title": "Blog"
        }
        return render(request, 'blog/post_edit.html', context)
    
    def post(self, request, pk):
        post = Post.objects.get(pk=pk)
        form = PostForm(request.POST)
        if form.is_valid():
            post.title = form.cleaned_data['title']
            post.content = form.cleaned_data['content']
            post.save()
            return redirect('blog:detail', pk=pk)
        
        form.add_error('폼이 유효하지 않습니다.')
        context = {
            'form': form,
            "title": "Blog"
        }
        return render(request, 'blog/post_edit.html', context)
        


# class Delete(DeleteView):
#     model = Post
#     success_url = reverse_lazy('blog:list')


class Delete(View):
    def post(self, request, pk): # post_id
        post = Post.objects.get(pk=pk)
        post.delete()
        return redirect('blog:list')
    
    # 클래스 자체에 아예 접근하지 못하게 -> LoginRequiredMixin
    # Login이 되었을 때만 삭제 버튼이 보이게


class DetailView(View):
    def get(self, request, pk): # post_id: 데이터베이스 post_id
        # list -> object 상세 페이지 -> 상세 페이지 하나의 내용
        # pk 값을 왔다갔다, 하나의 인자
        
        # 데이터베이스 방문
        # 해당 글
        # 장고 ORM (pk: 무조건 pk로 작성해야한다.)
        post = Post.objects.get(pk=pk)
        # 댓글
        comments = Comment.objects.filter(post=post)
        # 해시태그
        hashtags = HashTag.objects.filter(post=post)
        
        # 댓글 Form
        comment_form = CommentForm()
        
        # 태그 Form
        hashtag_form = HashTagForm()
        
        context = {
            "title": "Blog",
            'post': post,
            'comments': comments,
            'hashtags': hashtags,
            'comment_form': comment_form,
            'hashtag_form': hashtag_form,
        }
        
        return render(request, 'blog/post_detail.html', context)


### Comment
class CommentWrite(View):
    # def get(self, request):
    #     pass
    def post(self, request, pk):
        form = CommentForm(request.POST)
        # 해당 아이디에 해당하는 글 불러옴
        post = Post.objects.get(pk=pk)
        
        if form.is_valid():
            # 사용자에게 댓글 내용을 받아옴
            content = form.cleaned_data['content']    
            # 유저 정보 가져오기
            writer = request.user
            # 댓글 객체 생성, create 메서드를 사용할 때는 save 필요 없음
            comment = Comment.objects.create(post=post, content=content, writer=writer)
            # comment = Comment(post=post) -> comment.save()
            return redirect('blog:detail', pk=pk)
        
        # form.add_error(None, '폼이 유효하지 않습니다.')
        # errors = [error for error_list in form.errors.values() for error in error_list]
        
        hashtag_form = HashTagForm()
        context = {
            "title": "Blog",
            'post': post,
            'comments': post.comment_set.all(),
            'hashtags': post.hashtag_set.all(),
            'comment_form': form,
            'hashtag_form': hashtag_form
        }
        return render(request, 'blog/post_detail.html', context)


class CommentDelete(View):
    def post(self, request, pk): # comment_id
        # 지울 객체를 찾아야 한다. -> 댓글 객체
        comment = Comment.objects.get(pk=pk)
        # 상세페이지로 돌아가기
        post_id = comment.post.id
        # 삭제
        comment.delete()
        
        return redirect('blog:detail', pk=post_id)


### Tag
class HashTagWrite(View):
    def post(self, request, pk): # post_id
        form = HashTagForm(request.POST)
        # 해당 아이디에 해당하는 글 불러옴
        post = Post.objects.get(pk=pk)
        
        if form.is_valid():
            # 사용자에게 태그 내용을 받아옴
            name = form.cleaned_data['name']
            # 작성자 정보 가져오기
            writer = request.user
            # 댓글 객체 생성, create 메서드를 사용할 때는 save 필요 없음
            hashtag = HashTag.objects.create(post=post, name=name, writer=writer)
            # comment = Comment(post=post) -> comment.save()
            return redirect('blog:detail', pk=pk)
        
        form.add_error(None, '폼이 유효하지 않습니다.')
        comment_form = CommentForm()
        
        context = {
            'title': 'Blog',
            'post': post,
            'comments': post.comment_set.all(),
            'hashtags': post.hashtag_set.all(),
            'comment_form': comment_form,
            'hashtag_form': form
        }
        return render(request, 'blog/post_detail.html', context)


class HashTagDelete(View):
    def post(self, request, pk): # hashtag_id
        # 지울 객체를 찾아야 한다. -> 태그 객체
        hashtag = HashTag.objects.get(pk=pk)
        # 상세페이지로 돌아가기
        post_id = hashtag.post.id
        # 삭제
        hashtag.delete()
        
        return redirect('blog:detail', pk=post_id)

blog/templates/blog/form_error.html
<!-- form error 출력 -->

<div class="alert alert-danger">
    {{ form }}
</div>

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}

    <h2>제목: {{ post.title }}</h2>

    {% if post.writer == request.user %}
    <a href="{% url 'blog:edit' pk=post.pk %}" class="btn">수정</a>
    <form action="{% url 'blog:delete' pk=post.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" value="삭제" class="btn">
    </form>
    {% endif %}

    <p>내용: {{ post.content }}</p>
    <p>작성자: {{ post.writer }}</p>
    <p>작성일: {{ post.created_at }}</p>
    <hr>

    <!-- 작성 화면 -->
    <h3>댓글</h3>
    <form action="{% url 'blog:cm-write' pk=post.pk %}" method="post">
        {% csrf_token %}
        {% if comment_form.errors %}
            {% with form=comment_form %}
                {% include 'blog/form_error.html' %}
            {% endwith %}
        {% else %}
            {{ comment_form.content }}
        {% endif %}
        <input type="submit" value="댓글 작성">
    </form>
    <br>
    <!-- comments -->
    <!-- if 문 -->
    {% if comments %}
        <!-- for 문 -->
        <ul>
            {% for comment in comments %}
            <!-- 내용, 작성시간, 삭제 버튼 -->
                <li>{{ comment.content }} / {{ comment.created_at }}
                    {% if comment.writer == request.user %}
                        <form action="{% url 'blog:cm-delete' pk=comment.pk %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="X" class='btn'>
                        </form>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>댓글이 없습니다.</p>
    {% endif %}
    <hr>
    <!-- 태그작성 화면 -->
    <h3>해시태그</h3>
    <form action="{% url 'blog:tag-write' pk=post.pk %}" method="post">
        {% csrf_token %}
        {% if hashtag_form.errors %}
            {% with form=hashtag_form %}
                {% include 'blog/form_error.html' %}
            {% endwith %}
        {% else %}
            {{ hashtag_form.name }}
        {% endif %}
        <input type="submit" value="태그 작성">
    </form>
    {% if hashtags %}
    <ul>
        {% for hashtag in hashtags %}
        <li>
            {{ hashtag }}
            {% if hashtag.writer == request.user %}
                <form action="{% url 'blog:tag-delete' pk=hashtag.pk %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="X" class='btn'>
                </form>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <br>
    <p>해시태그가 없습니다.</p>
    {% endif %}


{% endblock %}

blog/templates/blog/post_detail_error.html
<!-- form error 출력 -->
{% comment %}
<div class="alert alert-danger">
    <ul>
        {% for errors in form.errors.values %}
            {% for error in errors %}
                <li>{{ error }}</li>
            {% endfor %}
        {% endfor %}
    </ul>
</div>
{% endcomment %}

{% extends 'base.html' %}

{% block content %}

<!-- form error -->
    <h2>제목: {{ post.title }}</h2>

    {% if post.writer == request.user %}
    <a href="{% url 'blog:edit' pk=post.pk %}" class="btn">수정</a>
    <form action="{% url 'blog:delete' pk=post.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" value="삭제" class="btn">
    </form>
    {% endif %}

    <p>내용: {{ post.content }}</p>
    <p>작성자: {{ post.writer }}</p>
    <p>작성일: {{ post.created_at }}</p>
    <hr>

    <!-- 작성 화면 -->
    <h3>댓글</h3>
    <form action="{% url 'blog:cm-write' pk=post.pk %}" method="post">
        {% csrf_token %}
        {{ comment_form }}
        <input type="submit" value="댓글 작성">
    </form>
    <br>
    <!-- comments -->
    <!-- if 문 -->
    {% if post.comments.all %}
        <!-- for 문 -->
        <ul>
            {% for comment in post.comments.all %}
            <!-- 내용, 작성시간, 삭제 버튼 -->
                <li>{{ comment.content }} / {{ comment.created_at }}
                    {% if comment.writer == request.user %}
                        <form action="{% url 'blog:cm-delete' pk=comment.pk %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="X" class='btn'>
                        </form>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>댓글이 없습니다.</p>
    {% endif %}
    <hr>
    <!-- 태그작성 화면 -->
    <h3>해시태그</h3>
    <form action="{% url 'blog:tag-write' pk=post.pk %}" method="post">
        {% csrf_token %}
        {{ hashtag_form.name }}
        <input type="submit" value="태그 작성">
    </form>
    {% if post.hashtags.all %}
    <ul>
        {% for hashtag in post.hashtags.all %}
        <li>
            {{ hashtag }}
            {% if hashtag.writer == request.user %}
                <form action="{% url 'blog:tag-delete' pk=hashtag.pk %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="X" class='btn'>
                </form>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <br>
    <p>해시태그가 없습니다.</p>
    {% endif %}

{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'base.html' %}

{% block content %}

{% if form.errors %}
    {% include 'blog/form_error.html' %}
{% else %}
    <form action="{% url 'blog:edit' pk=post.pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="수정">
    </form>
{% endif %}
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}

{% block content %}
    <p>블로그 글 작성 화면</p>
    <!-- 제목 -->
    <!-- 내용 -->
    <form action="{% url 'blog:write' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-outline-success">
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}
    <p>블로그 게시판 첫 화면입니다.</p>
    <form action="{% url 'blog:write' %}" method="get">
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ request.GET.next }}">
        <input type="submit" value="글 작성">
    </form>
    {# <a href="{% url 'blog:write' %}" class="btn btn-outline-success">글 작성</a> #}
    <!-- 조건문 -->
    <!-- 글이 있을 때: 테이블 출력 -->
    {% if posts %}
        <table class="table table-bordered">
            <thead class="table-light">
                <tr>
                    <td>제목</td>
                    <td>내용</td>
                    <td>작성자</td>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                    <tr>
                        <td><a href="{% url 'blog:detail' pk=post.pk %}" class="btn">{{ post.title }}</a></td>
                        <td>{{ post.writer }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <!-- 글이 없을 때: 문구 출력 -->
        <p>작성된 게시물이 없습니다.</p>
    {% endif %}
 
{% endblock %}